server:
  port: 8080   #端口号
  servlet:
    context-path: /    #项目访问路径

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.122.150:3306/akshare?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password: password