server:
  port: 8080   #端口号
  servlet:
    context-path: /    #项目访问路径

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.122.150:3306/akshare?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: p@ssw0rd

  jpa:
    show-sql: true  #显示SQL
    hibernate:
      ddl-auto: create #自动生成表

forest:
#  bean-id: config0     # 在spring上下文中bean的id, 默认值为forestConfiguration
#  backend: okhttp3     # 后端HTTP API： okhttp3，默认为okhttp3，也可以改为httpclient
  max-connections: 1000   # 连接池最大连接数，默认值为500
#  max-route-connections: 500 # 每个路由的最大连接数，默认值为500
#  timeout: 3000     # 请求超时时间，单位为毫秒, 默认值为3000
  connect-timeout: 3000   # 连接超时时间，单位为毫秒, 默认值为2000
  read-timeout: 3000
#  retry-count: 1     # 请求失败后重试次数，默认为0次不重试
#  ssl-protocol: SSLv3    # 单向验证的HTTPS的默认SSL协议，默认为SSLv3
#  logEnabled: true     # 打开或关闭日志，默认为true
#  log-request: true    # 打开/关闭Forest请求日志（默认为 true）
#  log-response-status: true  # 打开/关闭Forest响应状态日志（默认为 true）
#  log-response-content: true  # 打开/关闭Forest响应内容日志（默认为 false）




